### ISSUE TITLE
¿Puede integrase con IFTTT?

### ISSUE THREAD

**Issue by JMVS** [JoanManuelH/BHG-solidmation-PHP-REST-API#1]
Hola, recién me encuentro con este proyecto. Me gustaría saber si es posible integrarlo con la plataforma IFTTT (¿tal vez con webhooks?). Incluso me imagino que podría utilizarse el sensor de temperatura integrado para controlar otras cosas...
Gracias.
José.

**Comment by TheHackLife** [comment]
Hola, seguro que si, pero no sabría decirte como ya que usé muy poco IFTTT y nunca cree ninguna app en el sitio, dejo el issue abierto, quizá otra persona pueda ayudarte mejor
Saludos.

**Comment by JMVS** [comment]
Gracias por la pronta respuesta. Estuve probando un rato y lamenteblemente parece que sólo se puede recibir información (dispositivos y estado), no así realizar cambios (como encender o apagar). Hice la misma prueba en el sitio web (https://bgh-services.solidmation.com/control/Panel.aspx), y presenta los mismos síntomas. Parece que el método de acceso a través del sitio web está roto...
